<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            // Áo Dài products
            [
                'supplier_id' => 1,
                'category_id' => 1,
                'shop_id' => 1,
                'brand_id' => 1,
                'name' => 'Áo Dài Truyền Thống',
                'slug' => 'ao-dai-truyen-thong',
                'regular_price' => '2000000',
                'sale_price' => '1800000',
                'sku' => 'ADT001',
                'rating' => 4.8,
                'view_count' => 1200,
                'sold_count' => 500,
                'description' => 'Áo dài truyền thống cho dịp lễ hội.',
                'origin' => 'Vietnam',
                'meta_title' => 'Áo Dài Truyền Thống - Fashionista',
                'meta_description' => 'Khám phá các mẫu áo dài truyền thống tại Fashionista.',
                'meta_keyword' => 'áo dài, truyền thống, thời trang',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supplier_id' => 1,
                'category_id' => 1,
                'shop_id' => 1,
                'brand_id' => 1,
                'name' => 'Áo Dài Cưới',
                'slug' => 'ao-dai-cuoi',
                'regular_price' => '5000000',
                'sale_price' => '4500000',
                'sku' => 'ADC001',
                'rating' => 4.9,
                'view_count' => 1100,
                'sold_count' => 450,
                'description' => 'Áo dài cưới sang trọng cho cô dâu.',
                'origin' => 'Vietnam',
                'meta_title' => 'Áo Dài Cưới - Fashionista',
                'meta_description' => 'Mẫu áo dài cưới tuyệt đẹp tại Fashionista.',
                'meta_keyword' => 'áo dài, cưới, thời trang',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supplier_id' => 1,
                'category_id' => 1,
                'shop_id' => 1,
                'brand_id' => 1,
                'name' => 'Áo Dài Cách Tân',
                'slug' => 'ao-dai-cach-tan',
                'regular_price' => '3000000',
                'sale_price' => '2800000',
                'sku' => 'ADCT001',
                'rating' => 4.7,
                'view_count' => 1000,
                'sold_count' => 400,
                'description' => 'Áo dài cách tân hiện đại và trẻ trung.',
                'origin' => 'Vietnam',
                'meta_title' => 'Áo Dài Cách Tân - Fashionista',
                'meta_description' => 'Mẫu áo dài cách tân tại Fashionista.',
                'meta_keyword' => 'áo dài, cách tân, thời trang',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supplier_id' => 1,
                'category_id' => 1,
                'shop_id' => 1,
                'brand_id' => 1,
                'name' => 'Áo Dài Trẻ Em',
                'slug' => 'ao-dai-tre-em',
                'regular_price' => '1500000',
                'sale_price' => '1300000',
                'sku' => 'ADTE001',
                'rating' => 4.6,
                'view_count' => 800,
                'sold_count' => 300,
                'description' => 'Áo dài truyền thống cho trẻ em.',
                'origin' => 'Vietnam',
                'meta_title' => 'Áo Dài Trẻ Em - Fashionista',
                'meta_description' => 'Áo dài truyền thống cho trẻ em tại Fashionista.',
                'meta_keyword' => 'áo dài, trẻ em, thời trang',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supplier_id' => 1,
                'category_id' => 1,
                'shop_id' => 1,
                'brand_id' => 1,
                'name' => 'Áo Dài Họa Tiết',
                'slug' => 'ao-dai-hoa-tiet',
                'regular_price' => '2500000',
                'sale_price' => '2300000',
                'sku' => 'ADHT001',
                'rating' => 4.5,
                'view_count' => 700,
                'sold_count' => 200,
                'description' => 'Áo dài họa tiết độc đáo và đẹp mắt.',
                'origin' => 'Vietnam',
                'meta_title' => 'Áo Dài Họa Tiết - Fashionista',
                'meta_description' => 'Mẫu áo dài họa tiết tại Fashionista.',
                'meta_keyword' => 'áo dài, họa tiết, thời trang',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Quần Áo Nam products
            [
                'supplier_id' => 2,
                'category_id' => 2,
                'shop_id' => 2,
                'brand_id' => 2,
                'name' => 'Áo Thun Nam',
                'slug' => 'ao-thun-nam',
                'regular_price' => '200000',
                'sale_price' => '180000',
                'sku' => 'ATN001',
                'rating' => 4.6,
                'view_count' => 1000,
                'sold_count' => 450,
                'description' => 'Áo thun nam đơn giản và thoải mái.',
                'origin' => 'Vietnam',
                'meta_title' => 'Áo Thun Nam - Trendy Threads',
                'meta_description' => 'Khám phá các mẫu áo thun nam tại Trendy Threads.',
                'meta_keyword' => 'áo thun, nam, thời trang',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supplier_id' => 2,
                'category_id' => 2,
                'shop_id' => 2,
                'brand_id' => 2,
                'name' => 'Quần Jeans Nam',
                'slug' => 'quan-jeans-nam',
                'regular_price' => '500000',
                'sale_price' => '450000',
                'sku' => 'QJN001',
                'rating' => 4.7,
                'view_count' => 900,
                'sold_count' => 400,
                'description' => 'Quần jeans nam phong cách và bền đẹp.',
                'origin' => 'Vietnam',
                'meta_title' => 'Quần Jeans Nam - Trendy Threads',
                'meta_description' => 'Khám phá các mẫu quần jeans nam tại Trendy Threads.',
                'meta_keyword' => 'quần jeans, nam, thời trang',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supplier_id' => 2,
                'category_id' => 2,
                'shop_id' => 2,
                'brand_id' => 2,
                'name' => 'Áo Sơ Mi Nam',
                'slug' => 'ao-so-mi-nam',
                'regular_price' => '300000',
                'sale_price' => '270000',
                'sku' => 'ASM001',
                'rating' => 4.8,
                'view_count' => 1100,
                'sold_count' => 500,
                'description' => 'Áo sơ mi nam lịch lãm và phong cách.',
                'origin' => 'Vietnam',
                'meta_title' => 'Áo Sơ Mi Nam - Trendy Threads',
                'meta_description' => 'Khám phá các mẫu áo sơ mi nam tại Trendy Threads.',
                'meta_keyword' => 'áo sơ mi, nam, thời trang',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supplier_id' => 2,
                'category_id' => 2,
                'shop_id' => 2,
                'brand_id' => 2,
                'name' => 'Áo Khoác Nam',
                'slug' => 'ao-khoac-nam',
                'regular_price' => '700000',
                'sale_price' => '650000',
                'sku' => 'AKN001',
                'rating' => 4.9,
                'view_count' => 1200,
                'sold_count' => 550,
                'description' => 'Áo khoác nam ấm áp và thời trang.',
                'origin' => 'Vietnam',
                'meta_title' => 'Áo Khoác Nam - Trendy Threads',
                'meta_description' => 'Khám phá các mẫu áo khoác nam tại Trendy Threads.',
                'meta_keyword' => 'áo khoác, nam, thời trang',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supplier_id' => 2,
                'category_id' => 2,
                'shop_id' => 2,
                'brand_id' => 2,
                'name' => 'Quần Tây Nam',
                'slug' => 'quan-tay-nam',
                'regular_price' => '400000',
                'sale_price' => '380000',
                'sku' => 'QTN001',
                'rating' => 4.5,
                'view_count' => 800,
                'sold_count' => 300,
                'description' => 'Quần tây nam lịch lãm và thời trang.',
                'origin' => 'Vietnam',
                'meta_title' => 'Quần Tây Nam - Trendy Threads',
                'meta_description' => 'Khám phá các mẫu quần tây nam tại Trendy Threads.',
                'meta_keyword' => 'quần tây, nam, thời trang',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Áo Thun products
            [
                'supplier_id' => 3,
                'category_id' => 3,
                'shop_id' => 3,
                'brand_id' => 3,
                'name' => 'Áo Thun Trơn',
                'slug' => 'ao-thun-tron',
                'regular_price' => '150000',
                'sale_price' => '130000',
                'sku' => 'ATT001',
                'rating' => 4.5,
                'view_count' => 900,
                'sold_count' => 400,
                'description' => 'Áo thun trơn đơn giản và thoải mái.',
                'origin' => 'Vietnam',
                'meta_title' => 'Áo Thun Trơn - Chic Boutique',
                'meta_description' => 'Khám phá các mẫu áo thun trơn tại Chic Boutique.',
                'meta_keyword' => 'áo thun, trơn, thời trang',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supplier_id' => 3,
                'category_id' => 3,
                'shop_id' => 3,
                'brand_id' => 3,
                'name' => 'Áo Thun Họa Tiết',
                'slug' => 'ao-thun-hoa-tiet',
                'regular_price' => '180000',
                'sale_price' => '160000',
                'sku' => 'ATH001',
                'rating' => 4.6,
                'view_count' => 1000,
                'sold_count' => 450,
                'description' => 'Áo thun họa tiết đẹp mắt và thời trang.',
                'origin' => 'Vietnam',
                'meta_title' => 'Áo Thun Họa Tiết - Chic Boutique',
                'meta_description' => 'Khám phá các mẫu áo thun họa tiết tại Chic Boutique.',
                'meta_keyword' => 'áo thun, họa tiết, thời trang',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supplier_id' => 3,
                'category_id' => 3,
                'shop_id' => 3,
                'brand_id' => 3,
                'name' => 'Áo Thun Cổ Tròn',
                'slug' => 'ao-thun-co-tron',
                'regular_price' => '200000',
                'sale_price' => '180000',
                'sku' => 'ATCT001',
                'rating' => 4.7,
                'view_count' => 1100,
                'sold_count' => 500,
                'description' => 'Áo thun cổ tròn thoải mái và dễ mặc.',
                'origin' => 'Vietnam',
                'meta_title' => 'Áo Thun Cổ Tròn - Chic Boutique',
                'meta_description' => 'Khám phá các mẫu áo thun cổ tròn tại Chic Boutique.',
                'meta_keyword' => 'áo thun, cổ tròn, thời trang',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supplier_id' => 3,
                'category_id' => 3,
                'shop_id' => 3,
                'brand_id' => 3,
                'name' => 'Áo Thun Polo',
                'slug' => 'ao-thun-polo',
                'regular_price' => '250000',
                'sale_price' => '230000',
                'sku' => 'ATP001',
                'rating' => 4.8,
                'view_count' => 1200,
                'sold_count' => 550,
                'description' => 'Áo thun polo thanh lịch và sang trọng.',
                'origin' => 'Vietnam',
                'meta_title' => 'Áo Thun Polo - Chic Boutique',
                'meta_description' => 'Khám phá các mẫu áo thun polo tại Chic Boutique.',
                'meta_keyword' => 'áo thun, polo, thời trang',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supplier_id' => 3,
                'category_id' => 3,
                'shop_id' => 3,
                'brand_id' => 3,
                'name' => 'Áo Thun Dài Tay',
                'slug' => 'ao-thun-dai-tay',
                'regular_price' => '300000',
                'sale_price' => '280000',
                'sku' => 'ATDT001',
                'rating' => 4.9,
                'view_count' => 1300,
                'sold_count' => 600,
                'description' => 'Áo thun dài tay ấm áp và thời trang.',
                'origin' => 'Vietnam',
                'meta_title' => 'Áo Thun Dài Tay - Chic Boutique',
                'meta_description' => 'Khám phá các mẫu áo thun dài tay tại Chic Boutique.',
                'meta_keyword' => 'áo thun, dài tay, thời trang',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Đầm Váy products
            [
                'supplier_id' => 4,
                'category_id' => 4,
                'shop_id' => 4,
                'brand_id' => 4,
                'name' => 'Đầm Dự Tiệc',
                'slug' => 'dam-du-tiec',
                'regular_price' => '1000000',
                'sale_price' => '900000',
                'sku' => 'DDT001',
                'rating' => 4.8,
                'view_count' => 1000,
                'sold_count' => 500,
                'description' => 'Đầm dự tiệc sang trọng và quý phái.',
                'origin' => 'Vietnam',
                'meta_title' => 'Đầm Dự Tiệc - Urban Trends',
                'meta_description' => 'Khám phá các mẫu đầm dự tiệc tại Urban Trends.',
                'meta_keyword' => 'đầm, dự tiệc, thời trang',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supplier_id' => 4,
                'category_id' => 4,
                'shop_id' => 4,
                'brand_id' => 4,
                'name' => 'Đầm Công Sở',
                'slug' => 'dam-cong-so',
                'regular_price' => '800000',
                'sale_price' => '700000',
                'sku' => 'DCS001',
                'rating' => 4.7,
                'view_count' => 900,
                'sold_count' => 450,
                'description' => 'Đầm công sở lịch sự và trang nhã.',
                'origin' => 'Vietnam',
                'meta_title' => 'Đầm Công Sở - Urban Trends',
                'meta_description' => 'Khám phá các mẫu đầm công sở tại Urban Trends.',
                'meta_keyword' => 'đầm, công sở, thời trang',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supplier_id' => 4,
                'category_id' => 4,
                'shop_id' => 4,
                'brand_id' => 4,
                'name' => 'Đầm Dạo Phố',
                'slug' => 'dam-dao-pho',
                'regular_price' => '600000',
                'sale_price' => '500000',
                'sku' => 'DDP001',
                'rating' => 4.6,
                'view_count' => 800,
                'sold_count' => 400,
                'description' => 'Đầm dạo phố thoải mái và thời trang.',
                'origin' => 'Vietnam',
                'meta_title' => 'Đầm Dạo Phố - Urban Trends',
                'meta_description' => 'Khám phá các mẫu đầm dạo phố tại Urban Trends.',
                'meta_keyword' => 'đầm, dạo phố, thời trang',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supplier_id' => 4,
                'category_id' => 4,
                'shop_id' => 4,
                'brand_id' => 4,
                'name' => 'Đầm Maxi',
                'slug' => 'dam-maxi',
                'regular_price' => '1200000',
                'sale_price' => '1100000',
                'sku' => 'DM001',
                'rating' => 4.9,
                'view_count' => 1100,
                'sold_count' => 550,
                'description' => 'Đầm maxi dài thoải mái và sang trọng.',
                'origin' => 'Vietnam',
                'meta_title' => 'Đầm Maxi - Urban Trends',
                'meta_description' => 'Khám phá các mẫu đầm maxi tại Urban Trends.',
                'meta_keyword' => 'đầm, maxi, thời trang',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supplier_id' => 4,
                'category_id' => 4,
                'shop_id' => 4,
                'brand_id' => 4,
                'name' => 'Đầm Xòe',
                'slug' => 'dam-xoe',
                'regular_price' => '900000',
                'sale_price' => '800000',
                'sku' => 'DX001',
                'rating' => 4.8,
                'view_count' => 900,
                'sold_count' => 500,
                'description' => 'Đầm xòe nữ tính và duyên dáng.',
                'origin' => 'Vietnam',
                'meta_title' => 'Đầm Xòe - Urban Trends',
                'meta_description' => 'Khám phá các mẫu đầm xòe tại Urban Trends.',
                'meta_keyword' => 'đầm, xòe, thời trang',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Quần Jean products
            [
                'supplier_id' => 5,
                'category_id' => 5,
                'shop_id' => 5,
                'brand_id' => 5,
                'name' => 'Quần Jean Skinny',
                'slug' => 'quan-jean-skinny',
                'regular_price' => '600000',
                'sale_price' => '550000',
                'sku' => 'QJS001',
                'rating' => 4.7,
                'view_count' => 1100,
                'sold_count' => 500,
                'description' => 'Quần jean skinny ôm sát và thời trang.',
                'origin' => 'Vietnam',
                'meta_title' => 'Quần Jean Skinny - Vintage Vogue',
                'meta_description' => 'Khám phá các mẫu quần jean skinny tại Vintage Vogue.',
                'meta_keyword' => 'quần jean, skinny, thời trang',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supplier_id' => 5,
                'category_id' => 5,
                'shop_id' => 5,
                'brand_id' => 5,
                'name' => 'Quần Jean Rách',
                'slug' => 'quan-jean-rach',
                'regular_price' => '700000',
                'sale_price' => '650000',
                'sku' => 'QJR001',
                'rating' => 4.8,
                'view_count' => 1200,
                'sold_count' => 550,
                'description' => 'Quần jean rách cá tính và phong cách.',
                'origin' => 'Vietnam',
                'meta_title' => 'Quần Jean Rách - Vintage Vogue',
                'meta_description' => 'Khám phá các mẫu quần jean rách tại Vintage Vogue.',
                'meta_keyword' => 'quần jean, rách, thời trang',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supplier_id' => 5,
                'category_id' => 5,
                'shop_id' => 5,
                'brand_id' => 5,
                'name' => 'Quần Jean Ống Suông',
                'slug' => 'quan-jean-ong-suong',
                'regular_price' => '800000',
                'sale_price' => '750000',
                'sku' => 'QJOS001',
                'rating' => 4.9,
                'view_count' => 1300,
                'sold_count' => 600,
                'description' => 'Quần jean ống suông thoải mái và thời trang.',
                'origin' => 'Vietnam',
                'meta_title' => 'Quần Jean Ống Suông - Vintage Vogue',
                'meta_description' => 'Khám phá các mẫu quần jean ống suông tại Vintage Vogue.',
                'meta_keyword' => 'quần jean, ống suông, thời trang',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supplier_id' => 5,
                'category_id' => 5,
                'shop_id' => 5,
                'brand_id' => 5,
                'name' => 'Quần Jean Lưng Cao',
                'slug' => 'quan-jean-lung-cao',
                'regular_price' => '900000',
                'sale_price' => '850000',
                'sku' => 'QJLC001',
                'rating' => 4.8,
                'view_count' => 1200,
                'sold_count' => 550,
                'description' => 'Quần jean lưng cao thời trang và phong cách.',
                'origin' => 'Vietnam',
                'meta_title' => 'Quần Jean Lưng Cao - Vintage Vogue',
                'meta_description' => 'Khám phá các mẫu quần jean lưng cao tại Vintage Vogue.',
                'meta_keyword' => 'quần jean, lưng cao, thời trang',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supplier_id' => 5,
                'category_id' => 5,
                'shop_id' => 5,
                'brand_id' => 5,
                'name' => 'Quần Jean Trắng',
                'slug' => 'quan-jean-trang',
                'regular_price' => '1000000',
                'sale_price' => '950000',
                'sku' => 'QJT001',
                'rating' => 4.9,
                'view_count' => 1300,
                'sold_count' => 600,
                'description' => 'Quần jean trắng tinh tế và thời trang.',
                'origin' => 'Vietnam',
                'meta_title' => 'Quần Jean Trắng - Vintage Vogue',
                'meta_description' => 'Khám phá các mẫu quần jean trắng tại Vintage Vogue.',
                'meta_keyword' => 'quần jean, trắng, thời trang',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Giày Dép products
            [
                'supplier_id' => 6,
                'category_id' => 6,
                'shop_id' => 6,
                'brand_id' => 6,
                'name' => 'Giày Sneaker',
                'slug' => 'giay-sneaker',
                'regular_price' => '1500000',
                'sale_price' => '1400000',
                'sku' => 'GS001',
                'rating' => 4.8,
                'view_count' => 1000,
                'sold_count' => 500,
                'description' => 'Giày sneaker thể thao và thời trang.',
                'origin' => 'Vietnam',
                'meta_title' => 'Giày Sneaker - Couture Closet',
                'meta_description' => 'Khám phá các mẫu giày sneaker tại Couture Closet.',
                'meta_keyword' => 'giày, sneaker, thời trang',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supplier_id' => 6,
                'category_id' => 6,
                'shop_id' => 6,
                'brand_id' => 6,
                'name' => 'Giày Cao Gót',
                'slug' => 'giay-cao-got',
                'regular_price' => '2000000',
                'sale_price' => '1900000',
                'sku' => 'GCG001',
                'rating' => 4.9,
                'view_count' => 1100,
                'sold_count' => 550,
                'description' => 'Giày cao gót sang trọng và quý phái.',
                'origin' => 'Vietnam',
                'meta_title' => 'Giày Cao Gót - Couture Closet',
                'meta_description' => 'Khám phá các mẫu giày cao gót tại Couture Closet.',
                'meta_keyword' => 'giày, cao gót, thời trang',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supplier_id' => 6,
                'category_id' => 6,
                'shop_id' => 6,
                'brand_id' => 6,
                'name' => 'Giày Lười',
                'slug' => 'giay-luoi',
                'regular_price' => '1200000',
                'sale_price' => '1100000',
                'sku' => 'GL001',
                'rating' => 4.7,
                'view_count' => 900,
                'sold_count' => 450,
                'description' => 'Giày lười thoải mái và thời trang.',
                'origin' => 'Vietnam',
                'meta_title' => 'Giày Lười - Couture Closet',
                'meta_description' => 'Khám phá các mẫu giày lười tại Couture Closet.',
                'meta_keyword' => 'giày, lười, thời trang',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supplier_id' => 6,
                'category_id' => 6,
                'shop_id' => 6,
                'brand_id' => 6,
                'name' => 'Giày Sandal',
                'slug' => 'giay-sandal',
                'regular_price' => '1000000',
                'sale_price' => '900000',
                'sku' => 'GS001',
                'rating' => 4.6,
                'view_count' => 800,
                'sold_count' => 400,
                'description' => 'Giày sandal thoải mái và thời trang.',
                'origin' => 'Vietnam',
                'meta_title' => 'Giày Sandal - Couture Closet',
                'meta_description' => 'Khám phá các mẫu giày sandal tại Couture Closet.',
                'meta_keyword' => 'giày, sandal, thời trang',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supplier_id' => 6,
                'category_id' => 6,
                'shop_id' => 6,
                'brand_id' => 6,
                'name' => 'Giày Tây',
                'slug' => 'giay-tay',
                'regular_price' => '1800000',
                'sale_price' => '1700000',
                'sku' => 'GT001',
                'rating' => 4.9,
                'view_count' => 1200,
                'sold_count' => 600,
                'description' => 'Giày tây lịch lãm và sang trọng.',
                'origin' => 'Vietnam',
                'meta_title' => 'Giày Tây - Couture Closet',
                'meta_description' => 'Khám phá các mẫu giày tây tại Couture Closet.',
                'meta_keyword' => 'giày, tây, thời trang',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
