<?php

namespace App\Filament\App\Resources\ShopResource\Pages;

use App\Filament\App\Resources\ShopResource;
use App\Models\Shop;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\schema;


class ListShops extends ListRecords
{
    protected static string $resource = ShopResource::class;

    protected function getHeaderActions(): array
    {
        return [
//            Actions\CreateAction::make(),
        ];
    }
    protected function getTableQuery(): ?Builder
    {
        $user = Auth::user();
        if ($user){ // hiển thị shop cho những tài khoản có cùng shop_id
            return parent::getTableQuery()->where('id',$user->shop_id); // TODO: Change the autogenerated stub
        }

        // Nếu người dùng có vai trò "admin", trả về kết quả truy vấn gốc
        return parent::getTableQuery()->where('user_id', $user->id);
    }
}
