<?php

namespace App\Filament\App\Resources\SupplierResource\Pages;

use App\Filament\App\Resources\SupplierResource;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\Auth;

class ListSuppliers extends ListRecords
{
    protected static string $resource = SupplierResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\CreateAction::make(),
        ];
    }
    protected function getTableQuery(): ?Builder
    {
        $user = Auth::user();
        if (Auth::user()?->hasRole('admin')){
            return parent::getTableQuery()->where('shop_id',$user->shop_id); // TODO: Change the autogenerated stub
        }
        if ($user){
            return parent::getTableQuery()->where('shop_id',$user->shop_id); // TODO: Change the autogenerated stub
        }
        return parent::getTableQuery(); // TODO: Change the autogenerated stub
    }
}
